---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 1h
  values:
    fullnameOverride: renovate-operator
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
    route:
      enabled: true
      hostnames:
        - renovate.mortebrume.eu
      parentRefs:
        - name: envoy-internal
          namespace: network
    webhook:
      enabled: true
