---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-operator-crds
  interval: 1h
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-operator
  interval: 1h
  values:
    operator:
      enable_converter_ownership: true
    serviceMonitor:
      enabled: true
