---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shoko
spec:
  chartRef:
    kind: OCIRepository
    name: shoko
  interval: 1h
  values:
    controllers:
      shoko:
        type: statefulset # SQLite DB
        containers:
          app:
            image:
              repository: ghcr.io/shokoanime/server
              tag: daily@sha256:c74007b202d5b86e1043d04113b60d92931334cfdba9bbbf300a49ef4d3a831d
            command:
              - "/usr/src/app/build/Shoko.CLI" # Entrypoint needs root
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Europe/Paris
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 700m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8111
    route:
      app:
        hostnames:
          - shoko.mortebrume.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: shoko-config
        globalMounts:
          - path: /.shoko
      metadata:
        accessMode: ReadWriteOnce
        size: 20Gi
        suffix: metadata
        globalMounts:
          - path: /.shoko/Shoko.CLI/images
      media:
        existingClaim: media-library
        globalMounts:
          - path: /storage
