---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts/

resources:
  - ./namespace.yaml
  - ./jellyfin/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./storage/ks.yaml
