---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mortebrume-eu
spec:
  secretName: mortebrume-eu-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: mortebrume.eu
  dnsNames:
    - mortebrume.eu
    - "*.mortebrume.eu"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discopol-fr
spec:
  secretName: discopol-fr-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: discopol.fr
  dnsNames:
    - discopol.fr
    - "*.discopol.fr"
