---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mortebrume-eu
spec:
  dnsNames:
    - mortebrume.eu
    - "*.mortebrume.eu"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: mortebrume-eu-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discopol-fr
spec:
  dnsNames:
    - discopol.fr
    - "*.discopol.fr"
  duration: 160h
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: discopol-fr-tls
  usages:
    - digital signature
