---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: mortebrume-eu-tls
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: mortebrume-eu-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: mortebrume-eu-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: mortebrume-eu-tls
          property: *key
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: discopol-fr-tls
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: discopol-fr-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: discopol-fr-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: discopol-fr-tls
          property: *key
