---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: autobrr
spec:
  components:
    - ../../../../components/postgres/cert
    - ../../../../components/volsync
  dependsOn:
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/media/autobrr/app
  postBuild:
    substitute:
      APP: autobrr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
