---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mautrix-slack
spec:
  components:
    - ../../../../components/postgres/cert
  interval: 1h
  path: ./kubernetes/apps/matrix/mautrix-slack/app
  postBuild:
    substitute:
      APP: mautrix-slack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  wait: false
