---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  connection:
    bufferLimit: 8Mi
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
#   responseOverride:
#     - match:
#         statusCodes:
#           - type: Value
#             value: 403
#       redirect: &redirect
#         scheme: https
#         hostname: error.mortebrume.eu
#         path:
#           type: &pathType ReplaceFullPath
#           replaceFullPath: /403.html
#         statusCode: 302
#     - match:
#         statusCodes:
#           - type: Value
#             value: 404
#       redirect:
#         <<: *redirect
#         path:
#           type: *pathType
#           replaceFullPath: /404.html
#     - match:
#         statusCodes:
#           - type: Value
#             value: 500
#       redirect:
#         <<: *redirect
#         path:
#           type: *pathType
#           replaceFullPath: /500.html
#     - match:
#         statusCodes:
#           - type: Value
#             value: 502
#       redirect:
#         <<: *redirect
#         path:
#           type: *pathType
#           replaceFullPath: /502.html
#     - match:
#         statusCodes:
#           - type: Value
#             value: 503
#       redirect:
#         <<: *redirect
#         path:
#           type: *pathType
#           replaceFullPath: /503.html
#     - match:
#         statusCodes:
#           - type: Value
#             value: 504
#       redirect:
#         <<: *redirect
#         path:
#           type: *pathType
#           replaceFullPath: /504.html
---
# # yaml-language-server: $schema=https://schemas.mortebrume.eu/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.20.0.0/16
        - fd00::/48
  connection:
    bufferLimit: 8Mi
    maxAcceptPerSocketEvent: 0
  http2:
    initialStreamWindowSize: 2Mi
    initialConnectionWindowSize: 32Mi
    onInvalidMessage: TerminateStream
  # http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestReceivedTimeout: 0s
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: http
    - name: envoy-external
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
