---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: &app ${APP}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: *app
  oidc:
    provider:
      issuer: "https://idm.mortebrume.eu/oauth2/openid/${APP}"
    clientID: *app
    clientSecret:
      name: "${APP}-kanidm-oauth2-credentials"
    redirectURL: "https://${SUBDOMAIN:=${APP}}.mortebrume.eu/oauth2/callback"
    logoutPath: "/logout"
