---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-postgres
stringData:
  url: "postgresql://${DATABASE_OWNER:=${APP}}@pooler-rw.database.svc:5432/${APP}?sslmode=verify-full&sslcert=/var/run/secrets/postgresql/tls.crt&sslkey=/var/run/secrets/postgresql/tls.key&sslrootcert=/var/run/secrets/root-ca/ca.crt"
