---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: authentik-upstream
spec:
  targetRefs:
    - kind: Service
      name: authentik
      sectionName: "https"
      group: ""
  validation:
    wellKnownCACertificates: System
    hostname: auth.mortebrume.eu
