---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name authentik-tls # Used by LDAPS
spec:
  commonName: "auth.mortebrume.eu"
  dnsNames:
    - "auth.mortebrume.eu"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-long
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: *name
  usages:
    - digital signature
