---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-access
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-sm
  data:
    - secretKey: githubAppID
      remoteRef:
        key: FLUX_GITHUB_APP_ID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: FLUX_GITHUB_APP_INSTALLID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: FLUX_GITHUB_APP_PRIVKEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-sm
  data:
    - secretKey: token
      remoteRef:
        key: FLUX_GITHUB_WEBHOOK_TOKEN
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-sm
  data:
    - secretKey: age.agekey
      remoteRef:
        key: SOPS_PRIVATE_KEY
