---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-ipv6-pool
spec:
  blocks:
    - start: "2a01:4f8:242:4691::1"
      stop: "2a01:4f8:242:4691:ffff:ffff:ffff:ffff"
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-ipam
        operator: NotIn
        values:
          - disabled
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-ipv4-pool
spec:
  blocks:
    - cidr: 168.119.32.22/32
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^enp35s0$
