---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-db
  namespace: &namespace database
spec:
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      name: postgres-${APP}
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/components/database/base/postgres
  postBuild:
    substitute:
      APP: *app
      OWNER: ${DATABASE_OWNER:=${APP}}
      EXTENSIONS: ${q:='}${DATABASE_EXTENSIONS}${q:='}
      emptyArray: "[]"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
