---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mistgazer-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: github
        property: MISTGAZER_APP_KEY
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: mistgazer-auth-token
spec:
  appID: "1267040"
  installID: "66619414"
  auth:
    privateKey:
      secretRef:
        name: mistgazer-pem
        key: private_key_pem
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mistgazer-mortebrume
spec:
  target:
    template:
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: bW9ydGVicnVtZQo=
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: mistgazer-auth-token
