---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ferretdb-backup
spec:
  schedule: "6 30 0 * * *" # 6h30 everyday
  backupOwnerReference: self
  cluster:
    name: ferretdb
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
