---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaniop
spec:
  chartRef:
    kind: OCIRepository
    name: kaniop
  interval: 1h
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      dashboards:
        enabled: true
