---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kaniop
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.4.1
  url: oci://ghcr.io/pando85/helm-charts/kaniop
