---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yspotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        SPOTIFY_PUBLIC: "{{ .SPOTIFY_PUBLIC_KEY }}"
        SPOTIFY_SECRET: "{{ .SPOTIFY_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: yspotify
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yspotify-db
spec:
  refreshInterval: "0"
  target:
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        MONGO_ENDPOINT: |-
          "mongodb://yspotify:{{ .password }}@ferretdb.database.svc.cluster.local/yspotify
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
