---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ferretdb-cluster
spec:
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: ferretdb
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/ferretdb/cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: barman-r2-ferret
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ferretdb-app
spec:
  dependsOn:
    - name: ferretdb-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/ferretdb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
