---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

components:
  - ../../components/alerts/

resources:
  - ./namespace.yaml
  - ./cert-manager/ks.yaml
  - ./external-secrets/ks.yaml
  - ./onepassword/ks.yaml
  - ./trust-manager/ks.yaml
