---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: s3
  namespace: volsynkopia
spec:
  enabled: true
  trigger:
    schedule: 30 5 * * * # Every day at 5h30
  repository:
    repository: volsynkopia-r2-maintenance
