---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-client-ca
spec:
  isCA: true
  commonName: Postgres Authentication Certificate Authority
  subject:
    countries:
      - FR
    organizations:
      - mortebrume
  usages:
    - cert sign
    - crl sign
  nameConstraints:
    critical: true
    # Exclude everything. Only the CN may be set.
    excluded:
      dnsDomains: []
      ipRanges: []
      emailAddresses: []
      uriDomains: []
  duration: 87660h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  secretName: *name
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: &name postgres-client-ca
spec:
  ca:
    secretName: *name
