---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly
spec:
  components: []
  dependsOn:
    - name: dragonfly-operator
      namespace: dragonfly-system
  healthChecks:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      name: dragonfly
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/dragonfly/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
