---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-pihole
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-pihole
  interval: 30m
  values:
    fullnameOverride: externaldns-pihole
    provider:
      name: pihole
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: externaldns-pihole
            key: *name
    extraArgs:
      - --pihole-api-version=6
      - --pihole-server=http://oracle
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-internal
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - crd
    registry: noop
    domainFilters:
      - mortebrume.eu
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-pihole
