---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foundry
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/selfhosted/foundry/app
  postBuild:
    substitute:
      APP: foundry
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_DAILY_RETENTION: "2"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
