---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ca.yaml
  - ./certificate.yaml
  - ./cluster.yaml
  - ./externalSecret.yaml
  - ./objectStore.yaml
  - ./pooler.yaml
  - ./scheduledBackup.yaml
