---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ksgate
spec:
  chartRef:
    kind: OCIRepository
    name: ksgate
  interval: 1h
  values:
