---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: continuwuity
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/matrix/continuwuity/app
  postBuild:
    substitute:
      APP: continuwuity
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_STORAGECLASS: zfs-pv-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  wait: false
