---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 6Ti
  volumeName: matrix-storage
