---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kanidm-creds-provider
spec:
  interval: 1h
  url: https://github.com/mortebrume/kanidm-creds
  ref:
    branch: main
  secretRef:
    name: kanidm-creds-access
  provider: github
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-creds-repo
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: kanidm-creds-provider
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-creds-access
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        githubAppID: "1267040"
        githubAppInstallationID: "66619414"
        githubAppPrivateKey: "{{ .MISTGAZER_APP_KEY }}"
  dataFrom:
    - extract:
        key: github
