---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./gitRepository.yaml
  - ./httpRoute.yaml
  - ./kanidm.yaml
  - ./mutatingAdmissionPolicy.yaml
