---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafanaDashboard.yaml
  - ./helmRelease.yaml
  - ./mutatingAdmissionPolicy.yaml
  - ./ociRepository.yaml
  - ./prometheusRule.yaml
