---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-pv
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  compression: "zstd"
  dedup: "on"
  fstype: "zfs"
  poolname: "zroot/kube"
  shared: "yes"
provisioner: zfs.csi.openebs.io
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-pv-db
parameters:
  compression: "zstd"
  dedup: "off"
  fstype: "zfs"
  recordsize: "16k"
  poolname: "zroot/kube"
  shared: "yes"
provisioner: zfs.csi.openebs.io
