---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: BITWARDEN_MACHINE_KEY
            name: *name
            namespace: &namespace security
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: *namespace
        key: ca.crt
      organizationID: c3eea749-bf74-49e7-b1f3-b3b9013759cc
      projectID: 6adcb51e-245c-4a08-b141-b3b901379f53
